[package]
name = "aiome-contracts"
version = "1.0.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
zeroize = "1.8"
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true }
reqwest = { workspace = true }
base64 = { workspace = true }
chacha20poly1305 = { workspace = true }
rand = { workspace = true }
async-stream = { workspace = true }
bastion = { package = "bastion-core", version = "1.0.0", features = ["fs"] }
futures = { workspace = true }
axum = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
prost = { workspace = true, optional = true }

[build-dependencies]
tonic-build = { workspace = true }

[features]
axum = ["dep:axum"]
grpc = ["tonic", "prost"]


[lints]
workspace = true
