// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nurture サイドカーのステータス情報
 */
export type NurtureStatus = { 
/**
 * Nurture operation mode: "local" | "cloud" | "disabled"
 */
mode: string, 
/**
 * Current sidecar status
 */
status: string, 
/**
 * Connection URL
 */
url: string, };
