// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サイドカーエンジンの稼働状態
 */
export type SidecarStatus = { 
/**
 * api-server の状態
 */
apiServer: string, 
/**
 * key-proxy の状態
 */
keyProxy: string, 
/**
 * nurture の状態
 */
nurture: string, };
