// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * システムおよび環境のステータス情報
 */
export type SystemInfo = { 
/**
 * 稼働OS
 */
os: string, 
/**
 * Docker (または互換環境) の使用可否
 */
dockerAvailable: boolean, 
/**
 * 合計メモリ量（MB）
 */
totalMemoryMb: bigint, };
