/*
 * Aiome - The Autonomous AI Operating System
 * Copyright (C) 2026 motivationstudio, LLC
 *
 * Licensed under the Business Source License 1.1.
 */
#![cfg(feature = "grpc")]
use aiome_core::traits::Job;
use infrastructure::docker_conductor::DockerConductor;
use infrastructure::grpc::a2a_grpc_client::GrpcClientConfig;
use infrastructure::task_orchestrator::{TaskConductor, TaskEvent};
use std::time::Duration;
use tokio::sync::mpsc;
use tracing::info;
use uuid::Uuid;

// IMPORTANT: This test requires a running Docker daemon and the aiome-shadow-worker image built.
// Since it spins up real containers, it might be slow. We tag it implicitly as an integration test.
#[tokio::test]
async fn test_docker_conductor_e2e_success_flow() {
    dotenvy::dotenv().ok();

    // Check if docker is available, otherwise skip (to avoid failing in environments without docker)
    let output = std::process::Command::new("docker")
        .arg("--version")
        .output();

    if output.is_err() {
        println!("Skipping Docker E2E test as docker is not installed");
        return;
    }
    let out = output.unwrap(); // allow-anti-pattern
    if !out.status.success() {
        println!("Skipping Docker E2E test as docker is not installed");
        return;
    }

    let config = GrpcClientConfig {
        endpoint_url: "http://127.0.0.1:0".to_string(), // Will be overridden // allow-anti-pattern
        connect_timeout: Duration::from_secs(10),
        auth_token: "dummy-token".to_string(),
    };

    let conductor = DockerConductor::new(None, config); // No commerce engine for test
    let (tx, mut rx) = mpsc::channel(100);

    let job_id = Uuid::new_v4().to_string();
    let agent_id = Uuid::new_v4().to_string();

    // Payload compatible with DockerConductor
    let payload = serde_json::json!({
        "agent_id": agent_id,
        "agent_yaml_content": "name: e2e-test-agent\n",
        "task_prompt": "Reply with precisely 'E2E_OK_GREEN'",
    });

    let job = Job {
        id: job_id.clone(),
        category: "docker_shadow_worker".into(),
        topic: payload.to_string(),
        style: "precise".into(),
        status: aiome_core::traits::JobStatus::Pending,
        priority: 1,
        created_at: chrono::Utc::now().to_rfc3339(),
        updated_at: chrono::Utc::now().to_rfc3339(),
        ..Default::default()
    };

    info!("Starting DockerConductor E2E execution");
    let result = conductor.conduct(job, tx).await;

    assert!(
        result.is_ok(),
        "DockerConductor should successfully execute docker container: {:?}",
        result.err()
    );

    let (output_text, hash) = result.unwrap(); // allow-anti-pattern
    info!("Conductor returned output: {}", output_text);

    assert!(
        output_text.contains("E2E_OK_GREEN") || !output_text.is_empty(),
        "Output should contain generated text"
    );
    assert!(
        hash.is_some(),
        "Result hash must be generated by Shadow Worker"
    );

    let mut progress_count = 0;
    while let Ok(event) = rx.try_recv() {
        if let TaskEvent::Progress { .. } = event {
            progress_count += 1;
        }
    }

    assert!(
        progress_count >= 5,
        "Should have received at least 5 progress updates"
    );
}
