[package]
license = "Apache-2.0"
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
aiome-contracts = { path = "../aiome-contracts" }
serde.workspace = true
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
regex = "1.10"
tokio = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "postgres", "runtime-tokio-rustls"] }
async-trait = "0.1"
jsonwebtoken = "9.2"
ed25519-dalek = { version = "2.1", features = ["pkcs8", "rand_core"] }
secrecy = { workspace = true }
base64 = "0.22"
rand = "0.8"
sysinfo.workspace = true
tracing = { workspace = true }
nix = { workspace = true }
dirs = "5.0"
tokio-util = { workspace = true }
bastion = { package = "bastion-core", version = "1.0.0", features = ["fs", "net"] }
anyhow = { workspace = true }
config = { workspace = true }
utoipa = { workspace = true }
unicode-normalization = { workspace = true }
sha2.workspace = true
thiserror = { workspace = true }
img_hash = { workspace = true }
image = { workspace = true }
hkdf.workspace = true

[dev-dependencies]
tempfile = "3.8"
serial_test = { workspace = true }
